### ISSUE TITLE
FIX Delete_Contact Function

### ISSUE THREAD

**Issue by SimeonTsvetanov** [SimeonTsvetanov/Contacts-Manager-Project#4]
To start from the beggining:
    When adding a contact we are checking if the contact exist in our contacts list only by Number. I have tried to check by number and by name but it creates a bug. So to skip the bug we are checking only bu Number. 
    So lets say, that we create 3 diferent contacts with the same name but different numbers. - That is OK.

Now the issue:
When you enter the Delete_Contact function there should be an option to delete contact, by Name or to Delete Contact by Number. (Just because) If you select the delete by name:
you will delete all the contacts in the list with that name. 
To fight that we need to do something else!
So Idea is to create a function to check how many contacts we have with the same name. Then to print it, on the console And to attach a number to each of the 3: 1- 2- 3- to ask the user to fill in one of the 1,2,3 options.
Next, the function should identify the contact, we want to delete and return it as a result in the Delete_by_name function. Where the Delete by name function will do its magic.

Let's check this issue out.

**Comment by SimeonTsvetanov** [comment]
Just to add it's important to understand that this function should not be local, AS we have to use it again in the Update contact menu. When Updating the name.

**Comment by AntonovaAntonia** [comment]
So we select "Delete By Name" and on the console will be printed all selected contacts(name, number, city). We will iterate DB and we will save the information about this contacts in a dictionary with key - id(1, 2, 3..) and value(phone number). And when the user select number we will take the value and delete the contact. What about that?

**Comment by SimeonTsvetanov** [comment]
Great. I hate Dics. But this seems to be easier then working only in a FOR loop using counter to attach number to the choice and then pulling the name- number to a diff. var wich we return to the del_by_name function

**Comment by AntonovaAntonia** [comment]
> Great. I hate Dics. But this seems to be easier then working only in a FOR loop using counter to attach number to the choice and then pulling the name- number to a diff. var wich we return to the del_by_name function

Yes

**Comment by SimeonTsvetanov** [comment]
@AntonovaAntonia wants to be mentioned.

**Comment by AntonovaAntonia** [comment]
@SimeonTsvetanov

**Comment by SimeonTsvetanov** [comment]
Now after Internal Conversation. We have decided that we are not going to add the option to delete by NAME for now. But it might be added in the future. SO we will close this issue
