### ISSUE TITLE
Create the Update Contact Function

### ISSUE THREAD

**Issue by SimeonTsvetanov** [SimeonTsvetanov/Contacts-Manager-Project#5]
We need to create a function to update contacts.

**Comment by AntonovaAntonia** [comment]
What are the options for choosing a contact which we want to update? 
Maybe number and name like in delete command?

And than. We have three options of things which can be updated.

**Comment by SimeonTsvetanov** [comment]
Yep. The same way as in the Delete_contact. Not only but we can use the function to check for more names. If we create it. :D

**Comment by AntonovaAntonia** [comment]
Take it easy Master we are almost there @SimeonTsvetanov

**Comment by SimeonTsvetanov** [comment]
> Take it easy Master we are almost there @SimeonTsvetanov

Hahha

**Comment by AntonovaAntonia** [comment]
@SimeonTsvetanov I think we are almost there

**Comment by SimeonTsvetanov** [comment]
Ani has created the Option
