### ISSUE TITLE
We need to figure a way to Answer the Daily Questions for the Project.

### ISSUE THREAD

**Issue by SimeonTsvetanov** [SimeonTsvetanov/Contacts-Manager-Project#6]
Part of the Project task was to fill in daily a few questions. 
The purpose of which is that. When we finish with the Problem. It will be send to Others to review. 
And They can check the daily questions in order to see how we have progressed with the project.
The problem is to find a way to do it here. 
I have 2 ideas:
1- to fill them in the WIKI section
2- to create the in text.txt files in folders in the main repo (i'll create the files)

**Comment by AntonovaAntonia** [comment]
I will think about that. I don't know if it has to be in wiki section... i just don't know if it's purpose is that..

**Comment by AntonovaAntonia** [comment]
Soo, do you get this as a notification??

**Comment by SimeonTsvetanov** [comment]
We have solved this issue. Now we have folder with all the items in the main dir.

**Comment by SimeonTsvetanov** [comment]
Issue Was Solved
